baseurl         = "https://hammock.marketing/"
theme           = "hugo-casper-two"
languageCode    = "en-US"
disqusShortname = ""
paginate        = 6
#SectionPagesMenu = "main"
canonifyurls    = true

[params]
  title       = "Hammock Marketing"
  subtitle    = "Advancing Nonprofit Missions through Technology"
  copyright   = "© 2018"

  cover       = "https://res.cloudinary.com/adamprime/image/upload/v1541729333/cover5.jpg"
  description = "Advancing Nonprofit Missions through Technology"
  metaDescription = ""
  googleAnalytics = "UA-128042666-2"
  customCSS = []
  RSSLink = ""

  twitterName = "adamtervort"
#  fbName = "fakeghost"
#  githubName = "eueung"
  linkedinName = "adam.tervort"
  mediumName = "invisible_man"

  logo = "images/hm_logo_white.png"
  orgName = "Hammock Marketing"
  orgWebsite = "https://adamtervort.com"
  orgDescription = "Made with 🎶 by Adam"

  showSupport = false

  author = "Adam Tervort"
  authorAvatar = "https://res.cloudinary.com/adamprime/image/upload/v1541730175/adam_hat.png"
  authorLocation = "Kansas City, MO"
  authorWebsite = "https://adamtervort.com"
  authorDescription = "Customer success, baseball, jazz music, and 🌮"

  pageNotFoundTitle = "404 - Page not found"

  #casper or caspertwo
  singleViewStyle = "casper"

[permalinks]
  post = "/post/:slug/"

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 200

[[menu.main]]
  name = "About"
  url = "/about/"
  weight = 100

[[menu.main]]
  name = "Categories"
  url = "/categories/"
  weight = 99

[[menu.main]]
  name = "Courses"
  url = "https://learn.hammock.marketing/"
  weight = 95
