baseURL = "https://hammock.marketing/"
languageCode = "en-us"
title = "Hammock Marketing"
theme = "timer-hugo"

# We Used Ionicons Icon font for Icon, for more details check this link - https://ionicons.com/v2/

# Site Menus
[menu]
    # Navbar Menus
    [[menu.nav]]
        name    = "About"
        url     = "/about"
        weight  = 2
    [[menu.nav]]
        name    = "Service"
        url     = "/service"
        weight  = 3
    [[menu.nav]]
        name    = "Gallery"
        url     = "/gallery"
        weight  = 4
    [[menu.nav]]
        name    = "Blog"
        url     = "/blog"
        weight  = 5
    [[menu.nav]]
        name    = "Contact"
        url     = "/contact"
        weight  = 6

# Site Params
[params]
    home = "Home"
    dateFormat = "6 January 2006"
    #
    # You can use either an image or text as logo.
    # To use an image use 'logo' (logo itself) and 'logo_alt' (alternative text if image cannot displayed)
    # To use text as logo use 'logo_text'
    logo = "images/logo.png"
    logo_alt = "logo"
    #logo_text = "logo_text"

    # Banner Section
    [params.banner]
        enable  = true
        bgImage = "images/slider.jpg"
        heading = "COURSES AND ONLINE TRAINING FOR "
        description = "Learn the skills and techniques that will accelerate your performance and enhance your business and sales."
        btn     = true
        btnText = "VIEW COURSES"
        btnURL  = "https://learn.hammock.marketing/"
        [[params.banner.flipText]]
            title   = "BUSINESS OWNERS"
        [[params.banner.flipText]]
            title   = "ENTREPRENEURS"
        [[params.banner.flipText]]
            title   = "MARKETERS"
        [[params.banner.flipText]]
            title   = "DEVELOPERS"

    # Homepage About Section
    [params.about]
        enable  = true
        title   = "ABOUT ME"
        content = "Hello, I’m Adam. I have over ten years experience in website design, digital marketing, and customer success. I'm also an educator. I love sharing what I know with others. <br> <br> My goal is to help you be more productive and learn new skills. Online courses mean we can work together no matter where you're located at. (And even from your hammock!)"
        image   = "images/about/about.jpg"

    # Call to Action
    [params.cta]
        enable  = true
        title   = "Connect with me"
        content = "Have a question? Need some advice?"
        btnText = "Contact me"
        btnURL  = "/contact"

    # Portfolio Section On Homepage
    [params.portfolio]
        enable  = true
        title   = "Latest Courses"
        subtitle= ""

    # Feature Product Section
    [params.featureProduct]
        enable  = false
        title   = "SOME OF OUR FEATURES WORKS"
        subtitle= "Aliquam lobortis. Maecenas vestibulum mollis diam. Pellentesque auctor neque nec urna. Nulla sit amet est. Aenean posuere <br> tortor sed cursus feugiat, nunc augue blandit nunc, eu sollicitudin urna dolor sagittis lacus."

    # Footer section
    [params.footer]
        customized  = false # Set this variable to true if you customized the design.
        copyright_owner = "Hammock Marketing"
        copyright_since = "2018"
#        [[params.footer.social]]
#            icon = "ion-social-facebook"
#            link = "https://facebook.com"
        [[params.footer.social]]
            icon = "ion-social-twitter"
            link = "https://twitter.com/adamtervort/"
        [[params.footer.social]]
            icon = "ion-social-linkedin"
            link = "https://www.linkedin.com/in/adam-tervort/"
#        [[params.footer.social]]
#            icon = "ion-social-googleplus"
#            link = "https://googleplus.com"
#        [[params.footer.social]]
#            icon = "ion-social-github"
#            link = "https://github.com"
