# Site settings
baseurl = "https://hammock.marketing/"
title = "Hammock Marketing"
paginate = 5
buildFuture = true
theme           = "story"
languageCode    = "en-US"
# disqusShortname = "hammock-marketing" #This isn't supported by the theme yet but I'm leaving here until it is.


[[menu.social]]
  name = "Twitter"
  title = "fab fa-twitter-square"
  url = "https://twitter.com/adamtervort/"

[[menu.main]]
  name = "About"
  title = "About"
  url = "/about/"

[[menu.main]]
  name = "Courses"
  title = "Courses"
  url = "https://learn.hammock.marketing/"

[[menu.main]]
  name = "Archives"
  title = "Archives"
  url = "/archives/"

[params]
  author = "Adam Tervort"
  twitter = "adamtervort"
  classes = []
  mailchimp = "https://adamtervort.us3.list-manage.com/subscribe?u=ffbbac2138851a3fd1d76ff26&id=038329dcb8"

[outputs]
  home = ["HTML", "JSON", "RSS"]
  page = ["HTML"]
  section = ["HTML", "RSS"]
  taxonomy = ["HTML", "RSS"]
  taxonomyTerm = ["HTML", "RSS"]
