baseurl = "https://hammock.marketing"
title = "Hammock Marketing"
theme = "hugo-nederburg-theme"
languageCode = "en-us"
# Enable comments by entering your Disqus shortname
disqusShortname = ""
# Enable Google Analytics by entering your tracking code
googleAnalytics = "UA-128042666-2"
preserveTaxonomyNames = true
paginate = 5 #frontpage pagination

[params]
  # Unmark to use post folder for images. Default is static folder.
  #usepostimgfolder = true
  slogan = "Learn, Apply, Excel"
  description = "Optimize your learning and improve your business. All from the comfort of your hammock." # meta description
  # You need to set author to have an author bio. If you have a writer in the markdown file it will override this.
  author = "Adam Tervort"
  authorLink = "https://adamtervort.com/"
  bio = [
    "Adam is the founder of Hammock Marketing. He loves baseball, jazz music, and Taiwanese food."
  ]
  copyright = [
    "&copy; 2018 Adam Tervort",
  ]


  # Contact page
     # Since this template is static, the contact form uses www.formspree.io as a
     # proxy. The form makes a POST request to their servers to send the actual
     # email. Visitors can send up to a 1000 emails each month for free.
     #
     # What you need to do for the setup?
     #
     # - set your email address under 'email' below (it is also used in Gravatar for the bio).
     # - upload the generated site to your server
     # - send a dummy email yourself to confirm your account
     # - click the confirm link in the email from www.formspree.io
     # - you're done. Happy mailing!
  email = "adam@adamtervort.com"

  # Nav links in the side bar
  [[menu.main]]
  name = "Home"
  url = "/"
  weight = 1

  [[menu.main]]
  name = "Courses"
  url = "https://learn.hammock.marketing/"
  weight = 2

  [[menu.main]]
  name = "About"
  url = "about/"
  weight = 3

  [[menu.main]]
  name = "Get in touch"
  url = "contact/"
  weight = 4

# this will also be in author bio if there is no writer.
  [params.social]
#  facebook      = "full Social profile url in facebook"
#  googleplus    = "full profile url in googleplus"
#  email         = "email@example.com"
  twitter       = "https://twitter.com/adamtervort"
  linkedin      = "https://www.linkedin.com/in/adam-tervort/"
#  stackoverflow = "full profile url in stackoverflow"
#  instagram     = "full profile url in instagram"
  github        = "https://github.com/adamprime"
#  pinterest     = "full profile url in pinterest"
  rss           = true

# Add a writer, then use it in the markdown front matter like this: writer = "Lukas Herman"
