baseURL = "https://hammock.marketing"
languageCode = "en-us"
title = "Hammock Marketing"
theme = "LeaveIt"

paginate = 12
enableEmoji = true
enableRobotsTXT = true
googleAnalytics = "UA-128042666-2"

preserveTaxonomyNames = true

[blackfriday]
  hrefTargetBlank = true
  nofollowLinks = true
  noreferrerLinks = true

[Permalinks]
 posts = "/:year/:filename/"

[menu]
  [[menu.main]]
    name = "Blog"
    url = "/posts/"
    weight = 2

  [[menu.main]]
    name = "Categories"
    url = "/categories/"
    weight = 3

  [[menu.main]]
    name = "Courses"
    url = "https://learn.hammock.marketing"
    weight = 1

#  [[menu.main]]
#    name = "About Hammock Marketing"
#    url = "/about/"
#    weight = 4

[params]
    since = 2016
    author = "Adam Tervort"                           # Author's name
    avatar = "/images/me/logo.jpg"           # Author's avatar
    subtitle = "Optimize your learning and improve your business."         # Subtitle
    cdn_url = ""           # Base CDN URL
    home_mode = "" # post or other

    google_verification = ""

    description = "" # site description
    keywords = "" # site keywords

    beian = ""
    baiduAnalytics = ""

    license= '本文采用<a rel="license" href="http://creativecommons.org/licenses/by-nc/4.0/" target="_blank">知识共享署名-非商业性使用 4.0 国际许可协议</a>进行许可'

[params.social]
    GitHub = "adamprime"
    Twitter = "adamtervort"
    Email   = "adam@adamtervort.com"
#    Instagram = "xxoo"
#    Wechat = "/images/me/wechat.png"  # Wechat QRcode image
#    Facebook = "xxoo"
#    Telegram = "xxoo"
#    Dribbble = "xxoo"
    Medium = "@invisible_man"
